trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Src/*

pool:
  name: Hosted Windows 2019 with VS2019
  demands: msbuild

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

name: 4.19.$(Year:yy)$(DayOfYear)$(Rev:.rr)

steps:
- task: DeleteFiles@1
  displayName: 'Delete files from Build'
  inputs:
    SourceFolder: Build
    Contents: '**/*.csproj'

- task: DeleteFiles@1
  displayName: 'Delete files from Docs'
  inputs:
    SourceFolder: Docs
    Contents: '**/*.csproj'

- task: PowerShell@2
  displayName: 'PowerShell Script Set-Version.ps1'
  inputs:
    targetType: filePath
    filePath: './Build/Build.Scripts.Modules/CI/Set-Version.ps1'
    arguments: '-Path $(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: Build/.nuget/NuGet.config

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'
    arguments: '--output \lib\goodtocode-extensions --configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*.csproj'

- task: NuGetCommand@2
  displayName: 'NuGet pack Extensions.nuspec'
  inputs:
    command: pack
    packagesToPack: Build/Build.Content/NuGet/Extensions.nuspec
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'NuGet pack Extensions.Configuration.nuspec'
  inputs:
    command: pack
    packagesToPack: Build/Build.Content/NuGet/Extensions.Configuration.nuspec
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'NuGet pack Extensions.Drawing.nuspec'
  inputs:
    command: pack
    packagesToPack: Build/Build.Content/NuGet/Extensions.Drawing.nuspec
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'NuGet pack Extensions.Net.nuspec'
  inputs:
    command: pack
    packagesToPack: Build/Build.Content/NuGet/Extensions.Net.nuspec
    versioningScheme: byBuildNumber

- task: CopyFiles@2
  displayName: 'Copy Files Set-PackageQuality.ps1'
  inputs:
    SourceFolder: Build/Build.Scripts.Modules/CI
    Contents: 'Set-PackageQuality.ps1'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
